//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCAPI5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intern_table
    {
        public int Id { get; set; }
        public string Interns_name { get; set; }
    }
}
